### ISSUE TITLE
supported version

### ISSUE THREAD

**Issue by pishguy** [Cutta/MaterialTransitionAnimation#2]
merhaba,

which version of android supported with this library

**Comment by Cutta** [comment]
Merhaba @MahdiPishguy 
Actually this repository is not a library , it is just a practice for achieve some animation of this nice job. https://material.uplabs.com/posts/material-transition-animation
This project's min sdk is: 9. So you can run it on api level higher 9.

**Comment by pishguy** [comment]
@Cutta Thanks effendim

**Comment by Cutta** [comment]
You are welcome. Happy coding =)
